OnBoardV3/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnBoardV3.Controllers
{
    public class CustomerController : Controller
    {
        BLL.Operations Operation = new BLL.Operations();
        // GET: Customer
        public ActionResult Index()
        {
            var Customers = Operation.GetAllCustomers();
            return View(Customers);
        }
        // GET: Customer JSON
        public JsonResult GetAllCustomer()
        {
            var Customers = Operation.GetAllCustomers();
            return Json(Customers, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCustomerByID(int? id)
        {
            var Customers = Operation.GetCustomer(id);
            return Json(Customers, JsonRequestBehavior.AllowGet);
        }

        

        // POST: Customer/Create
        [HttpPost]
        public ActionResult Create(BLL.Model.Customer Customer)
        {
            try
            {
                var valid = Operation.SaveCustomer(Customer);
                return Json(new
                {
                    Valid = valid,
                    
                });
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public JsonResult Edit(BLL.Model.Customer Customer)
        {
            try
            {
                    var valid = Operation.UpdateCustomer(Customer);
                return Json(new
                {
                    Valid = valid,
                    //StudentsPartial = studentPartialViewHtml
                });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    result = "Error occured"
                    //StudentsPartial = studentPartialViewHtml
                });
            }
        }


        //// GET: Customer/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        // POST: Customer/Delete/5
        [HttpPost]
        public JsonResult Delete(int? id)
        {
            try
            {
                // TODO: Add update logic here
                var Customers = Operation.DeleteCustomer(id);
                return Json(new
                {
                    result = "sucessfuly edited"

                    //StudentsPartial = studentPartialViewHtml
                });
            }
            catch
            {
                return Json(new
                {
                    result = "error occured"

                    //StudentsPartial = studentPartialViewHtml
                });
            }
        }
    
}
}

OnBoardV3/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnBoardV3.Controllers
{
    public class ProductController : Controller
    {
        BLL.Operations Operation = new BLL.Operations();
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
        // GET: Product JSON
        public JsonResult GetAllProduct()
        {
            var products = Operation.GetAllProducts();
            return Json(products, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Create(BLL.Model.Product product)
        {
            try
            {
                // TODO: Add insert logic here
                var valid = TryUpdateModel(product);
                if (valid)
                {
                    var products = Operation.SaveProduct(product);
                    //return RedirectToAction("Index");
                    //Index();
                    //return RedirectToAction("Index");
                }
                return Json(new
                {
                    Valid = valid,
                    //Errors = GetErrorsFromModelState(),
                    //StudentsPartial = studentPartialViewHtml
                });
            }
            catch
            {
                return View();
            }
        }

        // POST: Product/Edit/5
        [HttpPost]
        public JsonResult Edit(BLL.Model.Product product)
        {
            try
            {
                //var valid = TryUpdateModel(product);
                //if (valid)
                //{
                    var products = Operation.UpdateProduct(product);
                //}
                //return RedirectToAction("Index");
                return Json(new
                {
                    Valid = products,
                    //Errors = GetErrorsFromModelState(),
                    //StudentsPartial = studentPartialViewHtml
                });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    result = "Error occured"
                    //StudentsPartial = studentPartialViewHtml
                });
            }
        }


        //// GET: Product/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        // POST: Product/Delete/5
        [HttpPost]
        public JsonResult Delete(int? id)
        {
            try
            {
                // TODO: Add update logic here
                var products = Operation.DeleteProduct(id);
                return Json(new
                {
                    result = "sucessfuly deleted"

                    //StudentsPartial = studentPartialViewHtml
                });
            }
            catch
            {
                return Json(new
                {
                    result = "error occured"

                    //StudentsPartial = studentPartialViewHtml
                });
            }
        }
    }
}

OnBoardV3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/knockoutjs")
    <script src="~/Scripts/knockout.validation.min.js"></script>     
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Products", "Index", "Product")</li>
                    <li>@Html.ActionLink("Customers", "Index", "Customer")</li>
                    <li>@Html.ActionLink("Store", "Index", "Store")</li>
                    <li>@Html.ActionLink("Sales", "Index", "Sales")</li>
                    <li>@Html.ActionLink("SalesSummary", "Index", "SalesSummary")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>